### ISSUE TITLE
文字列正規化関数を実装する

### ISSUE THREAD

**Issue by teramonagi** [uribo/zipangu#13]
[RのUnicode正規化関数（パッケージ）を作ってみた](https://abicky.net/2011/04/17/221357/)
これをモダナイズする

**Comment by teramonagi** [comment]
またはこれにならう
https://github.com/ikegami-yukino/neologdn/blob/master/README.rst

**Comment by yutannihilation** [comment]
stringiの関数ではだめなんですか？

**Comment by teramonagi** [comment]
はええよｗ

**Comment by teramonagi** [comment]
理解した、これのR版を実装する
https://github.com/neologd/mecab-ipadic-neologd/wiki/Regexp.ja#python-written-by-hideaki-t--overlast

**Comment by yutannihilation** [comment]
いや、`stri_trans_nfkc`とかの存在に気付いてないだけなのかなと思い...。知ってるなら大丈夫です！

**Comment by uribo** [comment]
stringiの関数をラップした [`str_conv_normalize()`](https://github.com/uribo/zipangu/blob/b8e3e7b684de654455814404b726ceab44f63076/R/convert-str.R#L66-L69) が用意されています。

``` r
library(zipangu)
x <- "\u2460"
print(x)
#> [1] "①"
str_conv_normalize(x, "nfkc")
#> [1] "1"
str_conv_normalize("㍿ホクソエム", to = "nfkc")
#> [1] "株式会社ホクソエム"
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by uribo** [comment]
neologdのリンクのような冗長な文字列を削除するのは正規化とは少し違うような。関数としてあっても良いと思いますが、 `str_conv_normalize()` とは分けたいです。

**Comment by paithiov909** [comment]
この話なんですが、[これ](https://github.com/paithiov909/rjavacmecab/blob/65544e1498fcef3aa7bd714b23560970eb30b707/R/utils.R#L41-L72)を移植してもらえませんか。こういう関数は個人的によくほしくなる場面があるのですが、自作パッケージに置いているとやや使い回ししづらいので、zipanguに似た関数があると便利に思います。

**Comment by uribo** [comment]
@paithiov909 ありがとうございます。neologdベースでの関数ですね。是非テストコード込みでプルリクエスト頂ければ幸いです。

一点、 [解析対象テキストの先頭と末尾の半角スペースは削除](https://github.com/neologd/mecab-ipadic-neologd/wiki/Regexp#解析対象テキストの先頭と末尾の半角スペースは削除) こちらが未実装なように思いますが、この機能を含める点についてはどうでしょうか。

**Comment by paithiov909** [comment]
@uribo つぎ足しで書いていたため、私的にはそこまで忠実に沿った実装は求めていませんでした。より忠実に同じような処理をするならだいたい次のような感じかと思うので、zipanguにはこちらを追加するつもりで作業しようと思います。

``` r
require(magrittr)
#>  要求されたパッケージ magrittr をロード中です
#> Warning: パッケージ 'magrittr' はバージョン 4.0.3 の R の下で造られました

normalize <- function(str) {
    res <- str %>%
        stringi::stri_trans_nfkc() %>%
        stringr::str_replace_all("\u2019", "\'") %>%
        stringr::str_replace_all("\u201d", "\"") %>%
        stringr::str_replace_all("[\\-\u02d7\u058a\u2010\u2011\u2012\u2013\u2043\u207b\u208b\u2212]+", "-") %>%
        stringr::str_replace_all("[\ufe63\uff0d\uff70\u2014\u2015\u2500\u2501\u30fc]+", enc2utf8("\u30fc")) %>%
        stringr::str_replace_all("([:blank:]){2,}", " ") %>%
        stringr::str_replace_all(
            paste0(
                "([\u0021-\u007e\uff10-\uff19\u3041-\u3093\u30a1-\u30f6\u30fc\u4e00-\u9fa0[:punct:]]*)",
                "[[:blank:]]*",
                "([\uff10-\uff19\u3041-\u3093\u30a1-\u30f6\u30fc\u4e00-\u9fa0[:punct:]]+)"
            ),
            "\\1\\2") %>%
        stringr::str_replace_all(
            paste0(
                "([\uff10-\uff19\u3041-\u3093\u30a1-\u30f6\u30fc\u4e00-\u9fa0[:punct:]]+)",
                "[[:blank:]]*",
                "([\u0021-\u007e[:punct:]]+)"
            ),
            "\\1\\2") %>%
        stringr::str_remove_all("[~\u223c\u223e\u301c\u3030\uff5e]+") %>%
        stringr::str_remove_all("^[:space:]|[:space:]$") %>%
        stringr::str_remove_all("[[:cntrl:]]+")
    return(res)
}

normalize("～～～スーパーーーーCoding the Matrix ＰＲＭＬ 副　読　本　アルゴリズム C　検索 エンジン 自作 入門 を 買い ました!！!")
#> [1] "スーパーCoding the Matrix PRML副読本アルゴリズムC検索エンジン自作入門を買いました!!!"
normalize("   南アルプスの　天然水-　Ｓｐａｒｋｉｎｇ　Ｌｅｍｏｎ　レモン一絞り   ")
#> [1] "南アルプスの天然水-Sparking Lemonレモン一絞り"
normalize("　南アルプスの　天然水-　Ｓｐａｒｋｉｎｇ*　Ｌｅｍｏｎ+　レモン一絞り　")
#> [1] "南アルプスの天然水-Sparking* Lemon+レモン一絞り"
```

<sup>Created on 2021-02-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

確認ですが、関数名はどうすればよいですか？

**Comment by uribo** [comment]
@paithiov909 関数名はお任せしますが、 `str_jconv` のドキュメントがあるので `str_normalize()` ではどうでしょうか。
