### ISSUE TITLE
Help collaborate on zipangu!

### ISSUE THREAD

**Issue by uribo** [uribo/zipangu#2]
zipanguパッケージの開発に協力者を募ります。

特に

- 既存の関数の保守
- ドキュメントの整備
- issueへの対応
- 新しい関数の提案、実装
- PRに対するレビュー

が主になるかと思います。
協力してやるぜ、という方はコメント欄等でお知らせください。

**Comment by yutannihilation** [comment]
日本語でおｋ？

**Comment by uribo** [comment]
もちろんOKです！ありがとうございます。👆ちょっとだけ追記しました

**Comment by kazutan** [comment]
どこまでできるかわかりませんが、可能な範囲でよければやりたいです!

**Comment by teramonagi** [comment]
はい！！！

**Comment by teuder** [comment]
私も協力させてください！

**Comment by Ryo-N7** [comment]
英語のdocumentation/広告、他にできることがあれば協力させてください！

**Comment by tomochan001** [comment]
こんにちは。仕事でトンボ付き漢数字の日付（昭和四十三年）を使うことがよくあり、ぜひ機能追加のお手伝いをしたいのですが、どうしたらよろしいでしょうか？

https://community-ja.exploratory.io/t/topic/654

**Comment by uribo** [comment]
@tomochan001 ご意見ありがとうございます。トンボ付き漢数字、確かに重要ですね。
すでにRでの実装コードを用意されているのであればプルリクエストを送っていただければ幸いです。

実装を含めた機能追加の要望ということであれば、こちらでコードを用意します。
ひとまずの処理を示します。zipanguには`kansuji2arabic_str()`があり、それを使うことで変換ができます。

``` r
library(zipangu)
convert_jdate(kansuji2arabic_str("昭和三十三年十二月一日"))
#> [1] "1958-12-01"
convert_jdate(kansuji2arabic_str("一九九〇年十月三一日"))
#> [1] "1990-10-31"
convert_jdate(kansuji2arabic_str("平成元年九月六日"))
#> [1] "1989-09-06"
```

<sup>Created on 2022-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by tomochan001** [comment]
@uribo ありがとうございます。コードはありません。
処理例拝見しました。まさに望んでいた形です！
