### ISSUE TITLE
convert_jdate()でNAが含まれるときに失敗する

### ISSUE THREAD

**Issue by uribo** [uribo/zipangu#20]
Slackより https://r-wakalang.slack.com/archives/C06QP6NJ0/p1594464408189700
``` r
library(zipangu)
date_error <- c("平成30年1月1日", "平成30年2月1日", NA)

date_error %>% 
    convert_jdate()
#> Error in if (sum(sapply(jyear, stringr::str_detect, pattern = "([0-9]{4}|[0-9]{4}.+年)", : missing value where TRUE/FALSE needed
```

<sup>Created on 2020-07-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
とりあえず簡単には `sum(, na.rm = TRUE)` にすればよさそう？

**Comment by uribo** [comment]
あれ、そうでしょうか。

とりあえずの打開策

```r
date_error %>% 
  purrr::map_at(which(!is.na(date_error)),
                convert_jdate) %>% 
  purrr::reduce(c)
)
```

`map_at()` 的なのを `convert_jdate()` に組み込むか？

**Comment by yutannihilation** [comment]
たしかになんかこういうの出てダメでした...

>  Error: Predicate functions must return a single `TRUE` or `FALSE`, not a missing value
