### ISSUE TITLE
CRAN check outputs NOTE: CRAN HTML validation note: trimming empty <dt>

### ISSUE THREAD

**Issue by indenkun** [uribo/zipangu#56]
@uribo 

CRANからすでにメールで連絡が行っておりご存知のことと思いますが、CRANチェックでNOTEがでており、2024-11-12までの修正が求められています。

一つは単純なタイプミスで、もう一つは`@InheritDotParams`に由来するとみられるものだと思います。
https://github.com/r-lib/roxygen2/issues/1671

複数のパッケージで類似するNOTEがでて修正を求められているようです。将来的に`@InheritDotParams`側で改善される可能性がありますが、現状簡単な解決策としては、次のように`@InheritDotParams`を使わない方法かと思います。
https://github.com/philips-software/latrend/issues/154

タイプミスの修正と`@InheritDotParams`を使用しないものでの修正を一応プルリクエストしておきます。

このプルリクエストをマージしないでの修正でも構いませんが、CRANからzinapguパッケージがArchiveのみとなるとやや不便になるのでCRANからパッケージがArchiveされる前に修正版の修正をお願いいたします。

すでに対策済み、投稿済みでしたらご容赦ください。

**Comment by uribo** [comment]
ご対応いただきましてありがとうございます。
CRANコメントへの対応は #56 で行っていただきましたので、
こちらで修正版の申請を行います。

**Comment by uribo** [comment]
ステータスは#58 でご確認ください

**Comment by uribo** [comment]
@indenkun 無事にCRANへの登録まで終えました。ご対応いただき、誠にありがとうございました。

**Comment by indenkun** [comment]
@uribo 早速ご対応いただきありがとうございます。
