### ISSUE TITLE
rlang::arg_match()の使い方についての質問

### ISSUE THREAD

**Issue by yutannihilation** [uribo/zipangu#7]
@uribo 
個人的には、デフォルトの引数が設定されている時は、その引数を指定しなくてもエラーとか警告は出ないことを期待するんですが、パッケージ中で`rlang::arg_match()`を使っている関数ではどういう挙動を想定しているでしょう？ たとえば以下のようなコード。

``` r
str_conv_hirakana <- function(str, to = c("hiragana", "katakana")) {
  rlang::arg_match(to)
  if (to == "hiragana") {
    stringi::stri_trans_general(str, "Katakana-Hiragana")
  } else {
    stringi::stri_trans_general(str, "Hiragana-Katakana")
  }
}

str_conv_hirakana("foo")
#> Warning in if (to == "hiragana") {: the condition has length > 1 and only the
#> first element will be used
#> [1] "foo"
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

よくあるのは、2行目を

``` r
  to <- rlang::arg_match(to)
```

としてオプションの1番目のものを自動で選ぶようにすることだと思ってるんですが、まあでもuriboがこう書いてるということはきっとこれが流行りの書き方ということだと想像していて（そういうissueも見かけたし： https://github.com/r-lib/rlang/issues/874 ）、意図を知っておきたいと思っての質問です。

**Comment by uribo** [comment]
@yutannihilation to引数の値をユーザに明示的に引数を指定させたい、が理由になります。

> オプションの1番目のものを自動で選ぶようにする
まさにこれをしたくないという意図です。

例えば次の処理で、ユーザが「い」と「う」を片仮名にしたいと思っていた場合、 `to <- rlang::arg_match(to)` では引数を省略した場合に `to = "hiragana"` が選択され、意図しない結果になってしまいます。さらにそれが暗黙的に実行されるのが問題だと思います。

``` r
x <- c("ア", "い", "う")
str_conv_hirakana <- function(str, to = c("hiragana", "katakana")) {
  to <- rlang::arg_match(to)
  if (to == "hiragana") {
    stringi::stri_trans_general(str, "Katakana-Hiragana")
  } else {
    stringi::stri_trans_general(str, "Hiragana-Katakana")
  }
}
# 省略してしまうと意図しない結果になってしまうかもしれない
str_conv_hirakana(x)
#> [1] "あ" "い" "う"
# こっちが求めている処理
str_conv_hirakana(x, to = "katakana")
#> [1] "ア" "イ" "ウ"
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`rlang::arg_match()` の結果を代入しないようにしておけば、少なくとも `to = "hiragana"` が選択されたことが出力されるので良いのかなと。

``` r
library(zipangu)
x <- c("ア", "い", "う")
str_conv_hirakana(x)
#> Warning in if (to == "hiragana") {: the condition has length > 1 and only the
#> first element will be used
#> [1] "あ" "い" "う"
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
> to引数の値をユーザに明示的に引数を指定させたい

うーん、なるほど。。明示的に指定させたいならデフォルト引数を設定するべきではない、というのが個人的な感覚で、あと tidyverse design guide にもそう書かれています：

> The absence of a default value should imply than an argument is required; the presence of a default should imply that an argument is optional.
(https://design.tidyverse.org/def-required.html)

が、まあここはRの言語としての限界で、あんまりイケてる解決法はなさそうなので（型がある言語ならもうちょい色々ありそう）、あとは好みの問題なのかなという気がします。

ということでそんなに強い意見があるわけではないですが、これを「`to = "hiragana"` が選択された」と読み解けるのは相当訓練されたRユーザーなのでは...

``` r
#> Warning in if (to == "hiragana") {: the condition has length > 1 and only the
#> first element will be used
```

**Comment by uribo** [comment]
う、tidyverse design guide...。ちょっと読んで検討してみます。

**Comment by yutannihilation** [comment]
解説のような解説じゃないような文章を書いたので興味あれば読んでください。まあこのissueはクローズってことでー。

https://notchained.hatenablog.com/entry/2019/12/23/221518

**Comment by uribo** [comment]
Thanks!

**Comment by uribo** [comment]
まだ結論はでないけど、ユーザが意図しない挙動を防ぐために、こう言う実装もありなのかなーと思えてきました。

```r
x <- c("ア", "い", "う")
str_conv_hirakana <- function(str, to) {
  to <- rlang::arg_match(to, values = c("hiragana", "katakana"))
  if (to == "hiragana") {
    stringi::stri_trans_general(str, "Katakana-Hiragana")
  } else {
    stringi::stri_trans_general(str, "Hiragana-Katakana")
  }
}
# to引数を省略することはできない
str_conv_hirakana(x)
#> Error in rlang::arg_match(to, values = c("hiragana", "katakana")) : 
#>   argument "to" is missing, with no default

# "hiragana" か "katakana" でないとエラー
str_conv_hirakana(x, "roman")
#> Error: `to` must be one of "hiragana" or "katakana"
```

**Comment by yutannihilation** [comment]
個人的にはそっちの方が好みです！（ユーザーが意識して指定しないといけないなら必須にして未指定はエラーにしたい）
