### ISSUE TITLE
漢数字（複数桁）の変換

### ISSUE THREAD

**Issue by nnawata** [uribo/zipangu#8]
新聞等（縦書き）でよく使われる以下の形式。(1,234,567,890,123)
一兆　二千三百四十五億　六千七百八十九万　百二十三(→1,234,567,890,123)
一兆　二三四五億　六七八九万　一二三(→1,234,567,890,123)
などの表記に対応したいのですが、なかなか骨が折れます。
関数追加があれば助かります。

**Comment by uribo** [comment]
ご意見ありがとうございます。`kansuji2arabic()` では処理しきれていない課題ですので、対応を検討いたします。

**Comment by uribo** [comment]
#23 にて対応
